---
title: "Instructivo"
---

# INGENIERÍA INDUSTRIAL UNIVERSIDAD DE CHILE

# TRABAJO SEMESTRAL

# IN5112 - DIRECCIÓN ESTRATÉGICA - SEMESTRE OTOÑO 2026

**PROFESORES COORDINADOR**: CLAUDIO PIZARRO T. - CARLOS CASTRO G. : NICOLÁS GONZÁLEZ S.

## 1\. Descripción

El trabajo semestral cubre el diagnóstico, evaluación y conclusión, la cual suele ir acompañada de una recomendación para la organización, de un problema estratégico, cuyo alcance responde a los objetivos del curso y de la carrera.

La selección del equipo podría estar coordinada con el curso de Diseño de Procesos de Negocios (IN5502) y/o Comportamiento Organizacional (IN5111), en caso que el/la alumno(a) los esté cursando en el mismo semestre. Lo anterior se realiza con el objetivo de facilitar la coordinación de integrantes, pero no existe relación en los trabajos semestrales a realizar en cada uno de estos cursos. A continuación se describe el trabajo del curso IN 5112.

El problema estratégico que se aborda puede ser alguno de los que se indican en los siguientes puntos, sin perjuicio que su definición será apoyada y posiblemente ajustada, de acuerdo al contexto y condiciones que el profesor y el/la tutor ayudante vean y perciban como necesario, a medida que avancen en su trabajo:

  * **Evolución histórica de una organización** (pública, privada, ONG) por un período suficiente de tiempo, que dé cuenta de las decisiones tomadas, del contexto inicial y de cómo evoluciona ese contexto; las razones que explican las decisiones, además de los resultados logrados y los aprendizajes que surgen.
  * **Decisiones estratégicas tomadas por una organización** (nacional o extranjera), para lo cual se revisa el contexto (interno y externo) en que se toma la decisión, las razones que explican esa decisión, los efectos observados y los aprendizajes constatados.
  * **Formulación de estrategias de una organización**, partiendo de su situación actual, enfrentada a un problema estratégico, analizando las variables clave que condicionan la creación de valor, público o privado, así como las estrategias alternativas y los efectos de mediano y largo plazo vinculados a cada una. Es clave analizar las razones o fundamentos que justifican las estrategias formuladas. Cabe la opción de aplicarlo a casos de emprendimiento o innovación.

Se trata en definitiva de analizar un problema estratégico, para lo cual se utilizan los conceptos, metodologías y bibliografía vistos en el curso, buscando especialmente la motivación de los alumnos, por lo que la organización y el problema a abordar debe ser de su interés. Es muy importante disponer de información de la organización y del mercado relevante.

El trabajo busca desarrollar la habilidad de pensamiento estratégico en torno a problemas de gestión en organizaciones, además de habilidades de trabajo en equipo y liderazgo. Todo esto forma parte de lo explicitado en el perfil de egreso del/la Ingeniero(a) Civil Industrial de la Universidad de Chile.

## 2\. Características

El trabajo se desarrolla durante el semestre en grupos de cuatro a cinco alumnos(as) y su evaluación se realiza por medio de entregas parciales de informes escritos, complementado con presentaciones de avance para efectos de seguimiento.

Cada grupo inscribe su caso de estudio por medio de una tarea en u-cursos, la que se habilita para estos fines.

### INGENIERÍA INDUSTRIAL UNIVERSIDAD DE CHILE

Cada grupo tendrá asignado un Tutor Ayudante, cuya función es apoyar y orientar al grupo en sus dudas a lo largo del semestre. El compromiso incluye al menos una reunión semanal y que la comunicación se realice formalmente a través de U-Cursos. Asimismo, una vez inscritos los casos de estudio, cada grupo contará con un Tutor(a) Profesional (TP - ICI de la UChile), cuya función principal es orientar en la definición del problema estratégico y en cómo abordarlo. Además, podrá apoyar en el análisis de estrategias y en el seguimiento del avance del trabajo, resolviendo dudas que pudieran surgir en el proceso. Se espera, al menos, una o dos reuniones con el TP enfocadas en el problema estratégico y en la formulación de estrategias. Si bien su compromiso con el grupo es acotado, los encuentros adicionales pueden coordinarse directamente con él o ella, dependiendo de su disponibilidad y motivación. El TP cuenta con experiencia profesional relevante. Muchos de ellos han participado en semestres anteriores en el curso, contribuyendo activamente a la formación de nuestros estudiantes.

La inclusión de referencias y respaldo de todos los datos que utilicen debe estar debidamente incorporada, tanto en los informes como en las presentaciones. Es clave la preocupación por justificar sus conclusiones, para lo cual se requieren análisis, métricas y datos. Se permite el uso de herramientas de inteligencia artificial como Chat GPT en los trabajos del curso, siempre que su uso sea complementario y no sustituya el análisis propio del estudiante. Cualquier asistencia de este tipo debe ser transparentada, mencionando su utilización cuando corresponda (por ejemplo, en notas al pie), y el contenido generado debe ser comprendido, editado y validado por el autor. Se pondrá especial atención a este aspecto en la revisión de los informes, resguardando así los principios de integridad académica y el desarrollo autónomo del trabajo intelectual.

## 3\. Entregables

Los entregables del trabajo del curso, que se realiza a lo largo del semestre son:

**3.1 Inscripción del caso de estudio (vía U-Cursos):** domingo 29 de Marzo a las 23:59 hrs.

**3.2 Presentaciones de avance 0, 1 y 2** son un espacio NO evaluado para que los alumnos reciban feedback del cuerpo docente y sus compañeros. Es importante señalar que para los alumnos que no presentan también es un espacio de aprendizaje, a partir de escuchar e interactuar con la experiencia de otros casos o problemas estratégicos.

**3.3 Defensa Final** es una presentación sin nota grupal pero que Si se evalúa de forma individual, formando parte de la nota de entregables (NE) de los informes.

  * **Presentación 0:** Presentación del caso de estudio. Se espera que los estudiantes tengan definida la empresa con la que van a trabajar y una propuesta de caso, así como avances en el marco conceptual y estructura de análisis.
  * **Presentación 1:** Presentación de avances, explicitando los objetivos del caso de estudio, la estructura de análisis (qué) y metodología (cómo) que van a utilizar, además de los análisis realizados a la fecha y las conclusiones preliminares que surgen.
  * **Presentación 2 (voluntaria):** Se reportan avances y ajustes a partir de las observaciones a la presentación anterior. Se incluyen los avances en los análisis estratégicos realizados y las conclusiones más relevantes que surgen.
  * **Defensa Final:** Todos los integrantes del grupo responden preguntas del Cuerpo Docente, considerando los análisis y conclusiones principales, además de la estructura y coherencia de los resultados. Cada grupo responde preguntas durante 20 minutos, incluso con participación de todo el curso. Para guiar esta instancia, se solicitará un documento breve (dos carillas) con la síntesis del problema estratégico, objetivo, estrategias propuestas y su justificación, que deben subir previo a la instancia.

### INGENIERÍA INDUSTRIAL UNIVERSIDAD DE CHILE

| PRESENTACIÓN                | FECHA                           |
| :-------------------------- | :------------------------------ |
| Presentación 0              | 31 de Marzo y 02 de Abril       |
| Presentación 1              | 21, 23, 28 y 30 de Abril        |
| Presentación 2 (voluntaria) | 26 y 28 de Mayo                 |
| Defensa Final               | 23, 25 y 30 de Junio y 02 Julio |

**3.3 Informes de avance (Entrega en PDF)** los que son un instrumento para sistematizar el trabajo realizado y estructurar el aprendizaje logrado. Es importante que consideren los aspectos conceptuales y metodológicos para abordar el caso. Estos entregables son acumulativos y deberán ir incorporando los comentarios que hace el cuerpo docente durante el semestre.

  * **Informe 0:** Incluye los objetivos y alcance del caso de estudio, indicando la organización en la que trabajarán, la definición del caso (problema estratégico) y una primera versión de la estructura de análisis y metodología. Importante es incorporar el feedback recibido en la presentación 0 - 2 carillas máximo, tamaño carta, letra número 11.
  * **Primer Informe de Avance:** (a) Caracterización de la empresa donde desarrolla el caso, (b) definición precisa del caso de estudio decisión o problema estratégico; y (c) cómo abordará el análisis del caso, indicando el plan de trabajo que contenga los hitos y plazos - 10 carillas máximo, tamaño carta, letra número 11.
  * **Segundo Informe de Avance:** Definición del problema estratégico y las variables clave que están involucradas en ese problema; y los análisis que ha realizado a la fecha y las principales conclusiones alcanzadas. Básicamente, se trata de tener el mayor avance posible a esta fecha, a fin de recibir la mayor y mejor retroalimentación posible - 15 carillas máximo, tamaño carta, letra número 11.
  * **Entrega Final:** Trabajo completo, con los resultados alcanzados, incorporando las observaciones del cuerpo docente - 15 carillas máximo, tamaño carta, letra número 11.

| ENTREGA       | FECHA       |
| :------------ | :---------- |
| Informe 0     | 03 de Abril |
| Informe 1     | 30 de Abril |
| Informe 2     | 29 de Mayo  |
| Informe Final | 03 de Julio |

**Todas las entregas son hasta las 23:59*

Dos veces por semestre se realiza un proceso de Autoevaluación Grupal. La metodología se enfoca en que cada integrante del grupo reciba una nota acorde al aporte y esfuerzo dedicado al desarrollo del trabajo.

## 4\. Evaluaciones

Los informes de avance se evalúan considerando tres dimensiones: contenido técnico, análisis y forma. En lo técnico, se valora una correcta definición del problema estratégico, con contexto, relevancia y variables clave bien justificadas, junto al uso pertinente de conceptos del curso. En el análisis, se espera una estructura clara y coherente, donde los datos (gráficos y tablas) estén bien integrados y fundamenten las conclusiones. En cuanto a la forma, se exige redacción clara, sin errores ortográficos, y cumplimiento del formato establecido, incluyendo la correcta rotulación de figuras y la mención de fuentes para los datos utilizados.

La nota final de cada alumno por el trabajo semestral considera la nota de entregables y el proceso de autoevaluación:

**4.1 Autoevaluación Grupal:** El proceso de autoevaluación que cada estudiante realiza en relación a su grupo de trabajo semestral, se relaciona a que cada integrante del grupo reciba una calificación final, acorde a su contribución durante el semestre, en la consecución de los objetivos de aprendizaje del citado trabajo, propuestos en cada una de las etapas de evaluación formal por parte del equipo docente.

El proceso de autoevaluación mide el grado de contribución personal al trabajo, y no el resultado de éste. De esta manera, la nota final del trabajo semestral estará ajustada por el nivel de esfuerzo percibido por cada uno y una de las integrantes del grupo, respecto al desempeño propio y de sus compañeros a lo largo del semestre.

## Metodología de autoevaluación

A continuación, se describe la metodología del proceso de autoevaluación:

  * La nota de entregables (NE) de cada estudiante se basa en la nota obtenida en el trabajo a lo largo del semestre, la cual ha sido definida por cada una de las notas con que el equipo docente ha evaluado cada uno de los informes y Defensa final entregados por cada grupo.

$NE = 0.15 * INF\_0 + 0.25 * INF\_1 + 0.6 * (0.65 * INF\_2 + 0.35 * PRES\_{final\_Individual})$

  * Se realizarán dos instancias de coevaluación:
      * La primera instancia será en semana 9, y
      * La segunda instancia será al finalizar el semestre, después de la entrega del Informe Final.
  * En cada instancia, cada estudiante deberá asignar 100 puntos entre los integrantes del grupo (incluido quién evalúa). Una mayor asignación de puntos se relaciona con un mayor aporte al trabajo grupal.
  * Al finalizar el semestre, con la segunda instancia de coevaluación, se obtiene el puntaje total recibido por cada estudiante $CT\_i$ correspondiente a la suma de los puntos asignados por todos los miembros del grupo.
  * Con este puntaje se calcula el Factor de Ajuste $FA\_i$ de cada integrante:
    $FA\_i = CT\_i / 100$
  * A partir de este factor, se calcula la Nota Personal final (NP) de cada estudiante (con nota máxima tope de 7.0):
    $NP = NE * FA\_i$
  * Finalmente, la Nota final del trabajo (NFT) viene dada por:
    $NFT = 0.5 * NE + 0.5 * NP$

### INGENIERÍA INDUSTRIAL UNIVERSIDAD DE CHILE

Un ejemplo de autoevaluación es el que se indica:

| Integrante | $CT\_i$ | $FA\_i$ | Nota Personal |
| :--------- | :------ | :------ | :------------ |
| 1          | 100     | 1.0     | 5.5           |
| 2          | 125     | 1.25    | 6.9           |
| 3          | 55      | 0.55    | 3.0           |
| 4          | 120     | 1.20    | 6.6           |

Se tiene un grupo de cuatro integrantes, cuya Nota de Entregables a lo largo del semestre es un 5.5 (NE). Definido lo anterior, la Tabla muestra el puntaje total recibido por cada estudiante ($CT\_i$) y la nota ajustada con la que será finalmente evaluado (NP).

Se observa que la suma de los $CT\_i$ es igual a 400. Esto debe ser así, pues cada evaluador(a) debe asignar en total 100 puntos entre los 4 integrantes del grupo (si fueran 5 integrantes la suma de $CT\_i$ sería de 500 puntos). Finalmente, si el grupo en conjunto decide que cada integrante mantendrá la nota con la que el equipo docente ha evaluado su trabajo grupal, entonces cada evaluador debe asignar la misma cantidad de puntos a cada integrante del grupo. Es decir, basado en el ejemplo, si el grupo decide que cada integrante debe mantener NE, en este caso 5.5, entonces cada evaluador deberá asignar 25 puntos a cada integrante del grupo (recuerda que se reparten 100 puntos, y que el grupo del ejemplo tiene 4 integrantes).

## Consideraciones importantes

La autoevaluación grupal debe ser un proceso realizado con un alto grado de responsabilidad y seriedad, pues debe reconocer el esfuerzo de cada uno y una de las integrantes, así como la falta de compromiso a lo largo del semestre. Además, es importante recordar que, dentro de los criterios mínimos de aprobación del curso para cada alumno, la nota final del trabajo grupal ajustada (NFT) debe ser mayor o igual a 4.0. Cualquier situación en que se considere que se ha faltado al código de ética será abordado, y en situaciones extremas será derivado a la Comisión Docente del Departamento de Ingeniería Industrial de la Universidad de Chile.

La asignación de puntajes de cada estudiante no depende de la nota global del trabajo grupal aplicado (NE), pues el puntaje total recibido sólo mide la contribución personal de cada estudiante. Este punto es importante ya que indica que no es necesario conocer NE para que cada grupo realice la autoevaluación, por lo que es probable que este proceso se realice antes de tener la información completa de los resultados finales de cada grupo. Recuerde que la autoevaluación grupal mide el grado de contribución personal al trabajo, y no el resultado de éste. Un integrante no podrá asignarse a sí mismo más del 50% de los puntos. Por ejemplo, si el grupo tiene cuatro integrantes hay 100 puntos para repartir, el o la estudiante no podrá asignarse más de 50 puntos.

Situaciones excepcionales serán analizadas con el cuerpo docente. Finalmente, es importante indicar que la autoevaluación de cada estudiante es tratada de forma confidencial, y serán revisadas sólo por el profesor y profesor auxiliar del curso. De esta manera, la información final que poseerá cada estudiante corresponderá a la nota final obtenida en esta evaluación, que estará relacionado al total de puntaje recibido.

## Formulario de autoevaluación

Para realizar la autoevaluación se ha dispuesto de un formulario especial que deberá completar cada estudiante. Este formulario estará disponible en la sección "Tareas" de u-cursos en el módulo de entrega de la autoevaluación. Recuerden que el total de puntos que deben distribuir es 100, por lo que no deben superar esta cantidad.

## 5\. Síntesis

El trabajo requiere que al inicio se definan los aspectos que se detallan a continuación, en forma clara y precisa. Para estos efectos es muy conveniente apoyarse en el Tutor Profesional, Tutor Ayudante, Coordinador y Profesores Auxiliar y de Cátedra. Aquí se juega parte importante del trabajo que sigue:

(a) **Definición del problema estratégico** que se aborda.

(b) **Objetivos general y específicos** del trabajo que se realizará para abordar este problema estratégico.

(c) **Marco conceptual** - explícita los tópicos bibliográficos específicos del análisis estratégico que utilizará para abordar el caso de estudio.

(d) **Estructura de análisis** - corresponde a los distintos análisis que realizará y cómo se conectan entre ellos para cumplir los objetivos propuestos. Este punto es clave porque determina la coherencia de su trabajo.

(e) **Metodología** corresponde a las etapas, actividades, resultados, plazos y responsables del trabajo que realizan para abordar el problema estratégico o caso de estudio.

(f) **Conclusiones a nivel estratégico** - corresponden a los entregables del trabajo, tanto parciales como finales, en específico, las acciones estratégicas bien fundamentadas mediante los análisis realizados.

(g) **Aprendizajes del curso**, considerando aspectos de contenidos y prácticos, después de haber terminado su trabajo en grupo.